// Engine (Rust) filter names and parameter labels by their English text (docs/I18N.md): the engine stays English,
// the app shows them in the UI language. labels.test.ts keeps this list equal to the engine schema.
import type { MessageDescriptor } from '@lingui/core';
import { msg } from '@lingui/core/macro';
// The worker reaches this module: the @lingui/core singleton keeps the catalog loader (i18n/index.ts) out of it.
import { i18n } from '@lingui/core';

export const ENGINE_LABELS: Record<string, MessageDescriptor> = {
  // Filter names
  'Accented Edges': msg`Accented Edges`,
  'Adaptive Wide Angle': msg`Adaptive Wide Angle`,
  'Add Noise': msg`Add Noise`,
  'Angled Strokes': msg`Angled Strokes`,
  Average: msg`Average`,
  'Bas Relief': msg`Bas Relief`,
  'Black & White': msg`Black & White`,
  Blur: msg`Blur`,
  'Blur More': msg`Blur More`,
  'Box Blur': msg`Box Blur`,
  'Brightness/Contrast': msg`Brightness/Contrast`,
  'Camera Raw Filter': msg`Camera Raw Filter`,
  'Chalk & Charcoal': msg`Chalk & Charcoal`,
  'Channel Mixer': msg`Channel Mixer`,
  Charcoal: msg`Charcoal`,
  Chrome: msg`Chrome`,
  Clouds: msg`Clouds`,
  'Color Balance': msg`Color Balance`,
  'Color Halftone': msg`Color Halftone`,
  'Color Lookup': msg`Color Lookup`,
  'Colored Pencil': msg`Colored Pencil`,
  'Content-Aware Scale': msg`Content-Aware Scale`,
  'Conté Crayon': msg`Conté Crayon`,
  Craquelure: msg`Craquelure`,
  Crosshatch: msg`Crosshatch`,
  Crystallize: msg`Crystallize`,
  Curves: msg`Curves`,
  Custom: msg`Custom`,
  Cutout: msg`Cutout`,
  'Dark Strokes': msg`Dark Strokes`,
  'De-Interlace': msg`De-Interlace`,
  Despeckle: msg`Despeckle`,
  'Difference Clouds': msg`Difference Clouds`,
  Diffuse: msg`Diffuse`,
  'Diffuse Glow': msg`Diffuse Glow`,
  Displace: msg`Displace`,
  'Dry Brush': msg`Dry Brush`,
  'Dust & Scratches': msg`Dust & Scratches`,
  Emboss: msg`Emboss`,
  Exposure: msg`Exposure`,
  Extrude: msg`Extrude`,
  Facet: msg`Facet`,
  Fibers: msg`Fibers`,
  'Field Blur': msg`Field Blur`,
  'Film Grain': msg`Film Grain`,
  'Filter Gallery': msg`Filter Gallery`,
  'Find Edges': msg`Find Edges`,
  Flame: msg`Flame`,
  Fragment: msg`Fragment`,
  Fresco: msg`Fresco`,
  'Gaussian Blur': msg`Gaussian Blur`,
  Glass: msg`Glass`,
  'Glowing Edges': msg`Glowing Edges`,
  'Gradient Map': msg`Gradient Map`,
  Grain: msg`Grain`,
  'Graphic Pen': msg`Graphic Pen`,
  'HSB/HSL': msg`HSB/HSL`,
  'Halftone Pattern': msg`Halftone Pattern`,
  'High Pass': msg`High Pass`,
  'Hue/Saturation': msg`Hue/Saturation`,
  'Ink Outlines': msg`Ink Outlines`,
  Invert: msg`Invert`,
  'Iris Blur': msg`Iris Blur`,
  'Lens Blur': msg`Lens Blur`,
  'Lens Correction': msg`Lens Correction`,
  'Lens Flare': msg`Lens Flare`,
  Levels: msg`Levels`,
  'Lighting Effects': msg`Lighting Effects`,
  Liquify: msg`Liquify`,
  Maximum: msg`Maximum`,
  Median: msg`Median`,
  Mezzotint: msg`Mezzotint`,
  Minimum: msg`Minimum`,
  Mosaic: msg`Mosaic`,
  'Mosaic Tiles': msg`Mosaic Tiles`,
  'Motion Blur': msg`Motion Blur`,
  'NTSC Colors': msg`NTSC Colors`,
  'Neon Glow': msg`Neon Glow`,
  'Note Paper': msg`Note Paper`,
  'Ocean Ripple': msg`Ocean Ripple`,
  Offset: msg`Offset`,
  'Oil Paint': msg`Oil Paint`,
  'Paint Daubs': msg`Paint Daubs`,
  'Palette Knife': msg`Palette Knife`,
  Patchwork: msg`Patchwork`,
  'Path Blur': msg`Path Blur`,
  'Perspective Warp': msg`Perspective Warp`,
  'Photo Filter': msg`Photo Filter`,
  Photocopy: msg`Photocopy`,
  'Photoshop Filter': msg`Photoshop Filter`,
  'Picture Frame': msg`Picture Frame`,
  Pinch: msg`Pinch`,
  Plaster: msg`Plaster`,
  'Plastic Wrap': msg`Plastic Wrap`,
  Pointillize: msg`Pointillize`,
  'Polar Coordinates': msg`Polar Coordinates`,
  'Poster Edges': msg`Poster Edges`,
  Posterize: msg`Posterize`,
  'Puppet Warp': msg`Puppet Warp`,
  'Radial Blur': msg`Radial Blur`,
  'Reduce Noise': msg`Reduce Noise`,
  Reticulation: msg`Reticulation`,
  Ripple: msg`Ripple`,
  'Rough Pastels': msg`Rough Pastels`,
  'Selective Color': msg`Selective Color`,
  'Shape Blur': msg`Shape Blur`,
  Sharpen: msg`Sharpen`,
  'Sharpen Edges': msg`Sharpen Edges`,
  'Sharpen More': msg`Sharpen More`,
  Shear: msg`Shear`,
  'Smart Blur': msg`Smart Blur`,
  'Smart Sharpen': msg`Smart Sharpen`,
  'Smudge Stick': msg`Smudge Stick`,
  Solarize: msg`Solarize`,
  Spatter: msg`Spatter`,
  Spherize: msg`Spherize`,
  'Spin Blur': msg`Spin Blur`,
  Sponge: msg`Sponge`,
  'Sprayed Strokes': msg`Sprayed Strokes`,
  'Stained Glass': msg`Stained Glass`,
  Stamp: msg`Stamp`,
  'Sumi-e': msg`Sumi-e`,
  'Surface Blur': msg`Surface Blur`,
  Texturizer: msg`Texturizer`,
  Threshold: msg`Threshold`,
  Tiles: msg`Tiles`,
  'Tilt-Shift': msg`Tilt-Shift`,
  'Torn Edges': msg`Torn Edges`,
  'Trace Contour': msg`Trace Contour`,
  Tree: msg`Tree`,
  Twirl: msg`Twirl`,
  Underpainting: msg`Underpainting`,
  'Unsharp Mask': msg`Unsharp Mask`,
  'Vanishing Point': msg`Vanishing Point`,
  Vibrance: msg`Vibrance`,
  'Water Paper': msg`Water Paper`,
  Watercolor: msg`Watercolor`,
  Wave: msg`Wave`,
  Wind: msg`Wind`,
  ZigZag: msg`ZigZag`,
  // Parameter labels
  Ambience: msg`Ambience`,
  Amount: msg`Amount`,
  'Amplitude Max': msg`Amplitude Max`,
  'Amplitude Min': msg`Amplitude Min`,
  Angle: msg`Angle`,
  'Angular Direction': msg`Angular Direction`,
  Arrangement: msg`Arrangement`,
  Aspect: msg`Aspect`,
  'Auto Scale': msg`Auto Scale`,
  Background: msg`Background`,
  'Background Level': msg`Background Level`,
  Balance: msg`Balance`,
  'Base Tree Type': msg`Base Tree Type`,
  'Black Intensity': msg`Black Intensity`,
  Blacks: msg`Blacks`,
  'Blade Curvature': msg`Blade Curvature`,
  'Blue Strength': msg`Blue Strength`,
  'Blur Angle': msg`Blur Angle`,
  'Blur Center': msg`Blur Center`,
  'Blur Focal Distance': msg`Blur Focal Distance`,
  'Blur Method': msg`Blur Method`,
  'Blur Shape': msg`Blur Shape`,
  'Bokeh Color': msg`Bokeh Color`,
  'Border Thickness': msg`Border Thickness`,
  'Branches Height': msg`Branches Height`,
  'Branches Thickness': msg`Branches Thickness`,
  Brightness: msg`Brightness`,
  'Bristle Detail': msg`Bristle Detail`,
  'Brush Detail': msg`Brush Detail`,
  'Brush Size': msg`Brush Size`,
  'Brush Type': msg`Brush Type`,
  'Cell Size': msg`Cell Size`,
  Center: msg`Center`,
  'Centered Blur': msg`Centered Blur`,
  'Chalk Area': msg`Chalk Area`,
  'Channel 1': msg`Channel 1`,
  'Channel 2': msg`Channel 2`,
  'Channel 3': msg`Channel 3`,
  'Channel 4': msg`Channel 4`,
  'Charcoal Area': msg`Charcoal Area`,
  'Charcoal Thickness': msg`Charcoal Thickness`,
  Cleanliness: msg`Cleanliness`,
  'Clear Amount': msg`Clear Amount`,
  Contrast: msg`Contrast`,
  Conversion: msg`Conversion`,
  Correction: msg`Correction`,
  'Crack Brightness': msg`Crack Brightness`,
  'Crack Depth': msg`Crack Depth`,
  'Crack Spacing': msg`Crack Spacing`,
  'Create New Fields by': msg`Create New Fields by`,
  'Crop Factor': msg`Crop Factor`,
  'Dark Intensity': msg`Dark Intensity`,
  Darkness: msg`Darkness`,
  Definition: msg`Definition`,
  Defoliate: msg`Defoliate`,
  Density: msg`Density`,
  Depth: msg`Depth`,
  Detail: msg`Detail`,
  Direction: msg`Direction`,
  'Direction Balance': msg`Direction Balance`,
  'Displacement Map': msg`Displacement Map`,
  Distance: msg`Distance`,
  Distortion: msg`Distortion`,
  'Distortion k2': msg`Distortion k2`,
  'Distortion k3': msg`Distortion k3`,
  Distribution: msg`Distribution`,
  Edge: msg`Edge`,
  'Edge Brightness': msg`Edge Brightness`,
  'Edge Fidelity': msg`Edge Fidelity`,
  'Edge Intensity': msg`Edge Intensity`,
  'Edge Simplicity': msg`Edge Simplicity`,
  'Edge Thickness': msg`Edge Thickness`,
  'Edge Width': msg`Edge Width`,
  'Effect Layers': msg`Effect Layers`,
  Eliminate: msg`Eliminate`,
  'End Point Speed (end)': msg`End Point Speed (end)`,
  'End Point Speed (start)': msg`End Point Speed (start)`,
  Feather: msg`Feather`,
  'Fiber Length': msg`Fiber Length`,
  'Fill Empty Area With': msg`Fill Empty Area With`,
  'Fix Blue/Yellow Fringe': msg`Fix Blue/Yellow Fringe`,
  'Fix Green/Magenta Fringe': msg`Fix Green/Magenta Fringe`,
  'Fix Red/Cyan Fringe': msg`Fix Red/Cyan Fringe`,
  'Flame Lines (Complexity)': msg`Flame Lines (Complexity)`,
  'Flame Type': msg`Flame Type`,
  'Flare Center': msg`Flare Center`,
  'Focal Length': msg`Focal Length`,
  Focus: msg`Focus`,
  Foreground: msg`Foreground`,
  'Foreground Level': msg`Foreground Level`,
  Frame: msg`Frame`,
  'Frame Color': msg`Frame Color`,
  'Frame Width': msg`Frame Width`,
  Gloss: msg`Gloss`,
  'Glow Amount': msg`Glow Amount`,
  'Glow Color': msg`Glow Color`,
  'Grain Color': msg`Grain Color`,
  'Grain Highlights': msg`Grain Highlights`,
  'Grain Size': msg`Grain Size`,
  'Grain Type': msg`Grain Type`,
  Graininess: msg`Graininess`,
  'Green Strength': msg`Green Strength`,
  'Grout Width': msg`Grout Width`,
  Height: msg`Height`,
  'Highlight Area': msg`Highlight Area`,
  'Highlight Fade Amount': msg`Highlight Fade Amount`,
  'Highlight Radius': msg`Highlight Radius`,
  'Highlight Strength': msg`Highlight Strength`,
  'Highlight Tonal Width': msg`Highlight Tonal Width`,
  Highlights: msg`Highlights`,
  Horizontal: msg`Horizontal`,
  'Horizontal Perspective': msg`Horizontal Perspective`,
  'Horizontal Scale': msg`Horizontal Scale`,
  'Image Balance': msg`Image Balance`,
  Input: msg`Input`,
  Intensity: msg`Intensity`,
  Interval: msg`Interval`,
  'Invert Texture': msg`Invert Texture`,
  Jag: msg`Jag`,
  Kernel: msg`Kernel`,
  'Leaves Amount': msg`Leaves Amount`,
  'Leaves Size': msg`Leaves Size`,
  Length: msg`Length`,
  'Lens Type': msg`Lens Type`,
  Level: msg`Level`,
  Light: msg`Light`,
  'Light Bokeh': msg`Light Bokeh`,
  'Light Direction': msg`Light Direction`,
  'Light Intensity': msg`Light Intensity`,
  'Light Position': msg`Light Position`,
  'Light Range Max': msg`Light Range Max`,
  'Light Range Min': msg`Light Range Min`,
  'Light/Dark Balance': msg`Light/Dark Balance`,
  'Lighten Grout': msg`Lighten Grout`,
  Lights: msg`Lights`,
  Margin: msg`Margin`,
  'Mask Incomplete Blocks': msg`Mask Incomplete Blocks`,
  Material: msg`Material`,
  'Matte Color': msg`Matte Color`,
  'Max Radius': msg`Max Radius`,
  'Maximum Offset': msg`Maximum Offset`,
  Mesh: msg`Mesh`,
  Method: msg`Method`,
  Mode: msg`Mode`,
  Monochromatic: msg`Monochromatic`,
  Name: msg`Name`,
  'No. of Levels': msg`No. of Levels`,
  'Noise Amount': msg`Noise Amount`,
  'Number of Generators': msg`Number of Generators`,
  'Number of Tiles': msg`Number of Tiles`,
  Opacity: msg`Opacity`,
  'Ornament Density': msg`Ornament Density`,
  Output: msg`Output`,
  'Paper Brightness': msg`Paper Brightness`,
  Path: msg`Path`,
  Paths: msg`Paths`,
  'Pattern Type': msg`Pattern Type`,
  'Pencil Width': msg`Pencil Width`,
  Pins: msg`Pins`,
  Posterization: msg`Posterization`,
  Preserve: msg`Preserve`,
  'Preserve Details': msg`Preserve Details`,
  'Protect Skin Tones': msg`Protect Skin Tones`,
  Puppet: msg`Puppet`,
  Quality: msg`Quality`,
  Radius: msg`Radius`,
  Randomize: msg`Randomize`,
  'Randomize Shapes': msg`Randomize Shapes`,
  Reach: msg`Reach`,
  'Red Strength': msg`Red Strength`,
  'Reduce Color Noise': msg`Reduce Color Noise`,
  Relief: msg`Relief`,
  Remove: msg`Remove`,
  'Remove Distortion': msg`Remove Distortion`,
  'Remove JPEG Artifact': msg`Remove JPEG Artifact`,
  Ridges: msg`Ridges`,
  Rig: msg`Rig`,
  'Ripple Magnitude': msg`Ripple Magnitude`,
  'Ripple Size': msg`Ripple Size`,
  Rotation: msg`Rotation`,
  Roundness: msg`Roundness`,
  Saturation: msg`Saturation`,
  Scale: msg`Scale`,
  Scaling: msg`Scaling`,
  Seed: msg`Seed`,
  'Shadow Fade Amount': msg`Shadow Fade Amount`,
  'Shadow Intensity': msg`Shadow Intensity`,
  'Shadow Radius': msg`Shadow Radius`,
  'Shadow Tonal Width': msg`Shadow Tonal Width`,
  Shadows: msg`Shadows`,
  Shape: msg`Shape`,
  'Sharpen Details': msg`Sharpen Details`,
  Sharpness: msg`Sharpness`,
  'Shear Curve': msg`Shear Curve`,
  Shine: msg`Shine`,
  Size: msg`Size`,
  Smoothness: msg`Smoothness`,
  Softness: msg`Softness`,
  'Solid Front Faces': msg`Solid Front Faces`,
  Source: msg`Source`,
  Speed: msg`Speed`,
  'Spray Radius': msg`Spray Radius`,
  'Square Size': msg`Square Size`,
  State: msg`State`,
  Strength: msg`Strength`,
  'Strobe Flashes': msg`Strobe Flashes`,
  'Strobe Strength': msg`Strobe Strength`,
  'Stroke Detail': msg`Stroke Detail`,
  'Stroke Direction': msg`Stroke Direction`,
  'Stroke Length': msg`Stroke Length`,
  'Stroke Pressure': msg`Stroke Pressure`,
  'Stroke Size': msg`Stroke Size`,
  'Stroke Width': msg`Stroke Width`,
  Style: msg`Style`,
  Stylization: msg`Stylization`,
  'Symmetric Distortion': msg`Symmetric Distortion`,
  Taper: msg`Taper`,
  Temperature: msg`Temperature`,
  Texture: msg`Texture`,
  'Texture Coverage': msg`Texture Coverage`,
  'Tile Size': msg`Tile Size`,
  Tint: msg`Tint`,
  Turbulent: msg`Turbulent`,
  Type: msg`Type`,
  'Undefined Areas': msg`Undefined Areas`,
  'Use Custom Color For Flames': msg`Use Custom Color For Flames`,
  Variance: msg`Variance`,
  Vertical: msg`Vertical`,
  'Vertical Perspective': msg`Vertical Perspective`,
  'Vertical Scale': msg`Vertical Scale`,
  Vignette: msg`Vignette`,
  'Vignette Amount': msg`Vignette Amount`,
  'Vignette Midpoint': msg`Vignette Midpoint`,
  'Wavelength Max': msg`Wavelength Max`,
  'Wavelength Min': msg`Wavelength Min`,
  'White Intensity': msg`White Intensity`,
  Whites: msg`Whites`,
  Width: msg`Width`,
};

export const engineLabel = (text: string) => (Object.hasOwn(ENGINE_LABELS, text) ? i18n._(ENGINE_LABELS[text]) : text);
