// Generated by app/src/app/webmcp.test.ts with UPDATE_TOOLS=1; do not edit.
export const PAGE_TOOLS = [
  {
    "name": "get_document",
    "title": "Get document",
    "description": "Returns the open document: name, size in pixels, bit depth, resolution, the active layer id and the layer tree (top layer last). Returns null when no document is open.",
    "inputSchema": {
      "type": "object",
      "properties": {}
    },
    "annotations": {
      "readOnlyHint": true
    }
  },
  {
    "name": "list_commands",
    "title": "List menu commands",
    "description": "Lists menu commands as English paths like \"Image > Adjustments > Invert\", whether each is enabled now, and checked: true for active toggles. When the UI language is not English, label holds the path as the user sees it. Pass query to filter by a case-insensitive substring of the path or label.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string"
        }
      }
    },
    "annotations": {
      "readOnlyHint": true
    }
  },
  {
    "name": "run_command",
    "title": "Run menu command",
    "description": "Runs one enabled menu command by its path from list_commands on the active layer and returns the updated document. Commands ending in \"…\" open a dialog in the page: fill and confirm it with your browser tools, or ask the user to.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        }
      },
      "required": [
        "path"
      ]
    },
    "annotations": {
      "consequentialHint": true
    }
  },
  {
    "name": "select_layer",
    "title": "Select layer",
    "description": "Makes the layer with this id (from get_document) the active layer that commands act on.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        }
      },
      "required": [
        "id"
      ]
    },
    "annotations": {}
  },
  {
    "name": "new_document",
    "title": "New document",
    "description": "Creates a new 8-bit RGB document with a white background, in pixels.",
    "inputSchema": {
      "type": "object",
      "required": [
        "width",
        "height"
      ],
      "properties": {
        "width": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65536
        },
        "height": {
          "type": "integer",
          "minimum": 1,
          "maximum": 65536
        }
      }
    },
    "annotations": {
      "consequentialHint": true
    }
  },
  {
    "name": "list_filters",
    "title": "List filters",
    "description": "Lists filters with their id and settable params (kind, range or choices, default). Pass query to filter by a case-insensitive substring of the id, label or group.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string"
        }
      }
    },
    "annotations": {
      "readOnlyHint": true
    }
  },
  {
    "name": "run_filter",
    "title": "Run filter",
    "description": "Applies a filter by id (from list_filters) to the active layer without opening a dialog. Params not given keep their defaults. Returns the updated document.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "params": {
          "type": "object"
        }
      },
      "required": [
        "id"
      ]
    },
    "annotations": {
      "consequentialHint": true
    }
  },
  {
    "name": "get_preview",
    "title": "Get preview",
    "description": "Returns the flattened document as a PNG image, scaled to fit maxSide pixels (default 1024), so you can see the result.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "maxSide": {
          "type": "integer",
          "minimum": 64,
          "maximum": 4096
        }
      }
    },
    "annotations": {
      "readOnlyHint": true
    }
  }
];
